SELECT o.YEAR
     , o.MONTH
     , u.GENDER
     , COUNT(*) USERS
FROM   USER_INFO u
     , (SELECT USER_ID
             , EXTRACT(YEAR FROM SALES_DATE) YEAR
             , EXTRACT(MONTH FROM SALES_DATE) MONTH
        FROM   ONLINE_SALE
        GROUP BY EXTRACT(YEAR FROM SALES_DATE)
               , EXTRACT(MONTH FROM SALES_DATE)
               , USER_ID
       ) o
WHERE  1=1
AND    u.GENDER IS NOT NULL
AND    o.USER_ID = u.USER_ID
GROUP BY o.YEAR, o.MONTH, u.GENDER
ORDER BY o.YEAR, o.MONTH, u.GENDER