SELECT M.PRODUCT_CODE, SUM(M.SALES) SALES
FROM   (
        SELECT P.PRODUCT_CODE, P.PRICE*O.SALES_AMOUNT SALES
        FROM   PRODUCT P
             , OFFLINE_SALE O
        WHERE 1=1
        AND   O.PRODUCT_ID = P.PRODUCT_ID
        ) M
GROUP BY M.PRODUCT_CODE
ORDER BY SALES DESC, M.PRODUCT_CODE