SELECT p.PRODUCT_ID
     , p.PRODUCT_NAME
     , SUM(NVL(o.SALES, 0)) TOTAL_SALES
FROM   FOOD_PRODUCT p
     , (SELECT p.PRODUCT_ID
             , NVL(p.PRICE, 0) * o.AMOUNT SALES
        FROM   FOOD_PRODUCT p
             , FOOD_ORDER o
        WHERE  1=1
        AND    o.PRODUCT_ID = p.PRODUCT_ID
        AND    TO_CHAR(o.PRODUCE_DATE, 'YYYYMM') = '202205'
       ) o
WHERE  1=1
AND    o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID