SELECT b.BOOK_ID
     , a.AUTHOR_NAME
     , TO_CHAR(b.PUBLISHED_DATE, 'YYYY-MM-DD') PUBLISHED_DATE
FROM   BOOK b
     , AUTHOR a
WHERE  1=1
AND    b.CATEGORY = '경제'
AND    a.AUTHOR_ID = b.AUTHOR_ID
ORDER BY b.PUBLISHED_DATE