SELECT MAX(i.REST_ID) REST_ID
     , MAX(i.REST_NAME) REST_NAME
     , MAX(i.FOOD_TYPE) FOOD_TYPE
     , MAX(i.FAVORITES) FAVORITES
     , MAX(i.ADDRESS) ADDRESS
     , ROUND(AVG(NVL(r.REVIEW_SCORE, 0)), 2) SCORE
FROM   REST_REVIEW r
     , REST_INFO i
WHERE  1=1
AND    i.ADDRESS LIKE '서울%'
AND    r.REST_ID = i.REST_ID
GROUP BY i.REST_ID
ORDER BY SCORE DESC, MAX(i.FAVORITES) DESC