SELECT MEMBER_ID
     , MEMBER_NAME
     , GENDER
     , TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') DATE_OF_BIRTH
FROM   MEMBER_PROFILE
WHERE  1=1
AND    TO_CHAR(DATE_OF_BIRTH, 'MM') = '03'
AND    GENDER = 'W'
AND    TLNO > ' '
ORDER BY MEMBER_ID